"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Loader2, Plus, Sparkles } from "lucide-react";
import { toast } from "sonner";

import { cn } from "@/lib/utils";
import {
  createNoteAction,
  generateNoteDraftAction,
} from "@/lib/actions";
import type { PickerOption } from "@/components/appointments/new-appointment-dialog";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";

type NoteType = "BIRP" | "DAP" | "SOAP";

const TEMPLATES: Record<
  NoteType,
  { key: string; label: string; placeholder: string }[]
> = {
  BIRP: [
    { key: "behavior", label: "Behavior", placeholder: "Observed behavior and client-reported concerns…" },
    { key: "intervention", label: "Intervention", placeholder: "Clinical interventions used this session…" },
    { key: "response", label: "Response", placeholder: "Client's response to the interventions…" },
    { key: "plan", label: "Plan", placeholder: "Plan for next session and homework…" },
  ],
  DAP: [
    { key: "data", label: "Data", placeholder: "Objective and subjective data…" },
    { key: "assessment", label: "Assessment", placeholder: "Clinical assessment and progress…" },
    { key: "plan", label: "Plan", placeholder: "Treatment plan and next steps…" },
  ],
  SOAP: [
    { key: "subjective", label: "Subjective", placeholder: "Client's reported experience…" },
    { key: "objective", label: "Objective", placeholder: "Observable, measurable findings…" },
    { key: "assessment", label: "Assessment", placeholder: "Clinical impression…" },
    { key: "plan", label: "Plan", placeholder: "Plan of care…" },
  ],
};

const selectClass =
  "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:opacity-50";

export function NoteComposer({
  clients,
  clinicians,
}: {
  clients: PickerOption[];
  clinicians: PickerOption[];
}) {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [pending, startTransition] = useTransition();
  const [generating, setGenerating] = useState(false);

  const [type, setType] = useState<NoteType>("BIRP");
  const [clientId, setClientId] = useState("");
  const [clinicianId, setClinicianId] = useState("");
  const [prompt, setPrompt] = useState("");
  const [presentingProblem, setPresentingProblem] = useState("");
  const [interventions, setInterventions] = useState("");
  const [sections, setSections] = useState<Record<string, string>>({});

  const disabled = clients.length === 0 || clinicians.length === 0;

  function reset() {
    setType("BIRP");
    setClientId("");
    setClinicianId("");
    setPrompt("");
    setPresentingProblem("");
    setInterventions("");
    setSections({});
  }

  async function onGenerate() {
    if (prompt.trim().length < 3) {
      toast.error("Add a short session summary to generate a draft");
      return;
    }
    setGenerating(true);
    const result = await generateNoteDraftAction({
      type,
      prompt,
      clientId: clientId || undefined,
      presentingProblem: presentingProblem || undefined,
      interventions: interventions
        ? interventions.split(",").map((s) => s.trim()).filter(Boolean)
        : undefined,
    });
    setGenerating(false);
    if (!result.ok) {
      toast.error(result.error);
      return;
    }
    setSections((prev) => ({ ...prev, ...result.sections }));
    toast.success("Draft generated by Jessie");
  }

  function onSave() {
    if (!clientId || !clinicianId) {
      toast.error("Select a client and clinician");
      return;
    }
    const required = TEMPLATES[type].map((f) => f.key);
    if (required.some((k) => !sections[k]?.trim())) {
      toast.error("Complete all sections before saving");
      return;
    }
    startTransition(async () => {
      const result = await createNoteAction({
        clientId,
        clinicianId,
        type,
        sections,
      });
      if (!result.ok) {
        toast.error(result.error);
        return;
      }
      toast.success(`${type} note created`);
      setOpen(false);
      reset();
      router.refresh();
    });
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button>
          <Plus className="h-4 w-4" /> New note
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>New clinical note</DialogTitle>
          <DialogDescription>
            Document a session with a structured note format — or let Jessie
            draft it for you.
          </DialogDescription>
        </DialogHeader>

        {disabled ? (
          <p className="my-4 rounded-md border border-dashed bg-muted/40 p-3 text-sm text-muted-foreground">
            Add at least one client and clinician (with a live database) before
            creating a note.
          </p>
        ) : (
          <div className="my-4 space-y-4">
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-2">
                <Label htmlFor="note-client">Client</Label>
                <select
                  id="note-client"
                  className={cn(selectClass)}
                  value={clientId}
                  onChange={(e) => setClientId(e.target.value)}
                >
                  <option value="">Select a client…</option>
                  {clients.map((c) => (
                    <option key={c.id} value={c.id}>
                      {c.name}
                    </option>
                  ))}
                </select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="note-clinician">Clinician</Label>
                <select
                  id="note-clinician"
                  className={cn(selectClass)}
                  value={clinicianId}
                  onChange={(e) => setClinicianId(e.target.value)}
                >
                  <option value="">Select a clinician…</option>
                  {clinicians.map((c) => (
                    <option key={c.id} value={c.id}>
                      {c.name}
                    </option>
                  ))}
                </select>
              </div>
            </div>

            <div className="space-y-2">
              <Label>Note format</Label>
              <Tabs value={type} onValueChange={(v) => setType(v as NoteType)}>
                <TabsList>
                  <TabsTrigger value="BIRP">BIRP</TabsTrigger>
                  <TabsTrigger value="DAP">DAP</TabsTrigger>
                  <TabsTrigger value="SOAP">SOAP</TabsTrigger>
                </TabsList>
              </Tabs>
            </div>

            <div className="space-y-2 rounded-md border bg-muted/30 p-3">
              <Label htmlFor="note-prompt" className="flex items-center gap-1.5">
                <Sparkles className="h-3.5 w-3.5 text-primary" /> Session summary
              </Label>
              <Textarea
                id="note-prompt"
                placeholder="Briefly describe the session; Jessie will draft the structured note…"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
              />
              <div className="grid gap-3 sm:grid-cols-2">
                <div className="space-y-1">
                  <Label htmlFor="note-problem" className="text-xs">
                    Presenting problem
                  </Label>
                  <Input
                    id="note-problem"
                    placeholder="e.g. Anxiety related to work transition"
                    value={presentingProblem}
                    onChange={(e) => setPresentingProblem(e.target.value)}
                  />
                </div>
                <div className="space-y-1">
                  <Label htmlFor="note-interventions" className="text-xs">
                    Interventions (comma-separated)
                  </Label>
                  <Input
                    id="note-interventions"
                    placeholder="e.g. CBT, mindfulness"
                    value={interventions}
                    onChange={(e) => setInterventions(e.target.value)}
                  />
                </div>
              </div>
              <Button
                type="button"
                variant="secondary"
                size="sm"
                onClick={onGenerate}
                disabled={generating}
              >
                {generating ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <Sparkles className="h-4 w-4" />
                )}
                Generate with Jessie
              </Button>
            </div>

            <div className="space-y-3">
              {TEMPLATES[type].map((field) => (
                <div key={`${type}-${field.key}`} className="space-y-2">
                  <Label htmlFor={`field-${field.key}`}>{field.label}</Label>
                  <Textarea
                    id={`field-${field.key}`}
                    placeholder={field.placeholder}
                    value={sections[field.key] ?? ""}
                    onChange={(e) =>
                      setSections((prev) => ({
                        ...prev,
                        [field.key]: e.target.value,
                      }))
                    }
                  />
                </div>
              ))}
            </div>
          </div>
        )}

        <DialogFooter>
          <Button type="button" variant="outline" onClick={() => setOpen(false)}>
            Cancel
          </Button>
          <Button type="button" onClick={onSave} disabled={pending || disabled}>
            {pending && <Loader2 className="h-4 w-4 animate-spin" />}
            Save note
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
