packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  sharp: true
  "@prisma/client": true
  "@prisma/engines": true
  prisma: true
  esbuild: true
  "@nestjs/core": false
  "@scarf/scarf": false

overrides:
  multer: "2.2.0"
  js-yaml: "4.3.1"
  glob: "10.5.0"
  picomatch: "4.0.4"
  brace-expansion: "2.1.4"
  webpack: "5.104.1"
  ajv: "8.18.0"
  tmp: "0.2.7"
  nanoid: "3.3.18"
  postcss: "8.5.23"
  deepmerge-ts: "8.0.0"
  sharp: "0.35.0"
  lodash: "4.18.1"
  fast-uri: "3.1.5"
